version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
  db:
    image: postgres:14.5
    volumes:
      - lws_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db

volumes:
  lws_postgres_data: